### ISSUE TITLE
Reproduction of the results in transcendent paper

### ISSUE THREAD

**Issue by IanWE** [s2labres/transcendent-release#1]
Hi, 

Sorry to bother you. I just tried to reproduce the results (F1 score on ICE with cred+conf) presented in paper "Transcending Transcend: Revisiting Malware Classification in the Presence of Concept Drift". 
I use the command below:
"python3 ice.py --dataset extended-features -k 10 -n -1 --pval-consider cal-only -t constrained-search  -c cred+conf --cs-max f1_k:0.90  --cs-con kept_pos_perc:0.85,kept_neg_perc:0.85 --rs-max f1_k --rs-min f1_r --rs-ceiling reject_total_perc:0.15 --rs-samples 100000"

The results are shown as ![微信截图_20240414181048](https://github.com/s2labres/transcendent-release/assets/17620569/725a3613-b7df-4c04-9343-be08f7fc1c9c) which is different from the one shown in the paper. Am I using a wrong setting?  Can you please provide an example?  
Many thanks.

**Comment by lcavallaro** [comment]
Hi Jianwen,

We released an errata corrige at https://s2lab.cs.ucl.ac.uk/downloads/transcending-errata_corrige.pdf as we identified a subtle but important bug in our original implementation that would enable data snooping.

The HEAD on GitHub has the bug fixed and the plot you obtain should be consistent with the one from the errata corrige pdf. Simply put, the plot in the paper shouldn’t existed in the first place - yet results are valid.

Hope this helps.

Thanks,
Lorenzo

Sent from my iPhone

On 14 Apr 2024, at 11:17, Jianwen Tian ***@***.***> wrote:

﻿

⚠ Caution: External sender


Hi,

Sorry to bother you. I just tried to reproduce the results (F1 score on ICE with cred+conf) presented in paper "Transcending Transcend: Revisiting Malware Classification in the Presence of Concept Drift".
I use the command below:
"python3 ice.py --dataset extended-features -k 10 -n -1 --pval-consider cal-only -t constrained-search -c cred+conf --cs-max f1_k:0.90 --cs-con kept_pos_perc:0.85,kept_neg_perc:0.85 --rs-max f1_k --rs-min f1_r --rs-ceiling reject_total_perc:0.15 --rs-samples 100000"

The results are shown as _20240414181048.png (view on web)<https://github.com/s2labres/transcendent-release/assets/17620569/725a3613-b7df-4c04-9343-be08f7fc1c9c> which is different from the one shown in the paper. Am I using a wrong setting? Can you please provide an example?
Many thanks.

**Comment by IanWE** [comment]
Dear Lorenzo,


I see. Thank you for your quick reply.&nbsp;


Jianwen
------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "s2labres/transcendent-release"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Apr 14, 2024 06:44 PM
***@***.***&gt;;
Cc:&nbsp;"- ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [s2labres/transcendent-release] Reproduction of the results in transcendent paper (Issue #1)





 Hi Jianwen, 
 
 We released an errata corrige at https://s2lab.cs.ucl.ac.uk/downloads/transcending-errata_corrige.pdf as we identified a subtle but important bug in our original implementation that would enable data snooping. 
 
 The HEAD on GitHub has the bug fixed and the plot you obtain should be consistent with the one from the errata corrige pdf. Simply put, the plot in the paper shouldn’t existed in the first place - yet results are valid. 
 
 Hope this helps. 
 
 Thanks, 
 Lorenzo 
 
 Sent from my iPhone 
 
 On 14 Apr 2024, at 11:17, Jianwen Tian ***@***.***&gt; wrote: 
 
 ﻿ 
 
 ⚠ Caution: External sender 
 
 
 Hi, 
 
 Sorry to bother you. I just tried to reproduce the results (F1 score on ICE with cred+conf) presented in paper "Transcending Transcend: Revisiting Malware Classification in the Presence of Concept Drift". 
 I use the command below: 
 "python3 ice.py --dataset extended-features -k 10 -n -1 --pval-consider cal-only -t constrained-search -c cred+conf --cs-max f1_k:0.90 --cs-con kept_pos_perc:0.85,kept_neg_perc:0.85 --rs-max f1_k --rs-min f1_r --rs-ceiling reject_total_perc:0.15 --rs-samples 100000" 
 
 The results are shown as _20240414181048.png (view on web)<https://github.com/s2labres/transcendent-release/assets/17620569/725a3613-b7df-4c04-9343-be08f7fc1c9c&gt; which is different from the one shown in the paper. Am I using a wrong setting? Can you please provide an example? 
 Many thanks.
